name: 检查 JSON 格式

on:
  push:
    branches: main
  pull_request:
    branches: main

  workflow_dispatch:  # 手动执行

jobs:
  check-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: "pypy-3.7". # Faster

      - name: Check JSON
        run: cat data.json | python -m json.tool | tee data.json
